<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-10 11:53

=======
# Generated by Django 5.1.3 on 2024-11-06 21:32

import django.db.models.deletion
from django.conf import settings
>>>>>>> 88fec20be35ff45424e5f321b77ef980e286a3fb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

<<<<<<< HEAD
    dependencies = []
=======
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
>>>>>>> 88fec20be35ff45424e5f321b77ef980e286a3fb

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
=======
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("update_on", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Publish")], default=0
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
>>>>>>> 88fec20be35ff45424e5f321b77ef980e286a3fb
        ),
    ]
